/*
id:,
prodName:,
prodPrice:,
prodDescription:,
prodImg:,
prodType:,
isFeatured: "true",

*/

/* 
Accessories
Foods
Toys
Vitamins 
Litters*/

const importAll = (context) => context.keys().map(context);
const accessories_images = importAll(
  require.context("../public/prod-photos/Accessories/", false, /\.(png)$/)
);
const foods_images = importAll(
  require.context("../public/prod-photos/Foods/", false, /\.(png)$/)
);
const toys_images = importAll(
  require.context("../public/prod-photos/Toys/", false, /\.(png)$/)
);
const wellness_images = importAll(
  require.context("../public/prod-photos/Wellness/", false, /\.(png)$/)
);

export default [
  //ACCESSORIES
  {
    id: 1,
    prodName: "Raised Ceramic Bowl",
    prodPrice: 100,
    prodDescription: "desc",
    prodImg: accessories_images[0],
    prodType: "Accessories",
  },
  {
    id: 2,
    prodName: "Black Ceramic Bowl",
    prodPrice: 300,
    prodDescription: "desc",
    prodImg: accessories_images[1],
    prodType: "Accessories",
    isFeatured: true,
  },
  {
    id: 3,
    prodName: "Automatic Feeder (Single)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[2],
    prodType: "Accessories",
  },
  {
    id: 4,
    prodName: "Automatic Feeder (Double)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[3],
    prodType: "Accessories",
  },
  {
    id: 5,
    prodName: "Black Body Leash",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[4],
    prodType: "Accessories",
  },
  {
    id: 6,
    prodName: "Purple Thin Leash",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[5],
    prodType: "Accessories",
  },
  {
    id: 8,
    prodName: "Retractable Leash",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[6],
    prodType: "Accessories",
  },
  {
    id: 9,
    prodName: "Simple Scratcher",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[7],
    prodType: "Accessories",
  },
  {
    id: 10,
    prodName: "Oval Corrugated Scratcher",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[8],
    prodType: "Accessories",
    isFeatured: "true",
  },
  {
    id: 11,
    prodName: "Vertical Scratcher",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[9],
    prodType: "Accessories",
  },
  {
    id: 12,
    prodName: "Simple Cat Tower",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[10],
    prodType: "Accessories",
  },
  {
    id: 13,
    prodName: "Cat Tower with Scratcher",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[11],
    prodType: "Accessories",
  },
  {
    id: 14,
    prodName: "Luxury Multi-floor Tower",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[12],
    prodType: "Accessories",
  },
  {
    id: 15,
    prodName: "Metal Water Fountain",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[13],
    prodType: "Accessories",
  },
  {
    id: 16,
    prodName: "Elegant Ceramic Fountain",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[14],
    prodType: "Accessories",
    isFeatured: "true",
  },
  {
    id: 17,
    prodName: "Little Bud Ceramic Fountain",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: accessories_images[15],
    prodType: "Accessories",
  },
  //Foods
  {
    id: 18,
    prodName: "Chicken and Tuna (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[0],
    prodType: "Foods",
  },
  {
    id: 19,
    prodName: "Salmon with Dill Special (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[1],
    prodType: "Foods",
  },
  {
    id: 20,
    prodName: "Salmon and Duck (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[2],
    prodType: "Foods",
  },
  {
    id: 21,
    prodName: "Turkey and Whitefish (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[3],
    prodType: "Foods",
  },
  {
    id: 22,
    prodName: "Venison and Duck Special (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[4],
    prodType: "Foods",
    isFeatured: "true",
  },
  {
    id: 23,
    prodName: "Beef with Liver (Wet)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[5],
    prodType: "Foods",
  },
  {
    id: 24,
    prodName: "Chicken with Liver (Wet)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[6],
    prodType: "Foods",
  },
  {
    id: 25,
    prodName: "Salmon with Liver (Wet)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[7],
    prodType: "Foods",
  },
  {
    id: 26,
    prodName: "Beef for Kittens (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[8],
    prodType: "Foods",
  },
  {
    id: 27,
    prodName: "Chicken for Kittens (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[9],
    prodType: "Foods",
  },
  {
    id: 28,
    prodName: "Ocean Fish for Kittens (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[10],
    prodType: "Foods",
  },
  {
    id: 29,
    prodName: "Salmon for Kittens (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[11],
    prodType: "Foods",
  },
  {
    id: 30,
    prodName: "Turkey for Kittens (Dry)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[12],
    prodType: "Foods",
  },
  {
    id: 31,
    prodName: "Beef for Kittens (Wet)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[13],
    prodType: "Foods",
  },
  {
    id: 32,
    prodName: "Chicken for Kittens (Wet)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[14],
    prodType: "Foods",
  },
  {
    id: 33,
    prodName: "Salmon for Kittens (Wet)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[15],
    prodType: "Foods",
  },
  {
    id: 34,
    prodName: "TREATS (Tuna Flavored)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[16],
    prodType: "Foods",
  },
  {
    id: 35,
    prodName: "TREATS (Salmon Flavored)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[17],
    prodType: "Foods",
  },
  {
    id: 36,
    prodName: "TREATS (Chicken Flavored)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: foods_images[18],
    prodType: "Foods",
  },
  //TOYS
  {
    id: 35,
    prodName: "Wiggle Tail",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[0],
    prodType: "Toys",
  },
  {
    id: 36,
    prodName: "Feather Hider",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[1],
    prodType: "Toys",
  },
  {
    id: 37,
    prodName: "Ball Shooter",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[2],
    prodType: "Toys",
  },
  {
    id: 38,
    prodName: "Sneaky Snake",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[3],
    prodType: "Toys",
  },
  {
    id: 39,
    prodName: "Red Laser",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[4],
    prodType: "Toys",
  },
  {
    id: 40,
    prodName: "Ball Hunter",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[5],
    prodType: "Toys",
  },
  {
    id: 41,
    prodName: "Treat Seeker",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[6],
    prodType: "Toys",
    isFeatured: "true",
  },
  {
    id: 42,
    prodName: "Rolly Balls",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[7],
    prodType: "Toys",
  },
  {
    id: 43,
    prodName: "Wooden Cat Wheel",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[8],
    prodType: "Toys",
  },
  {
    id: 44,
    prodName: "Sleek Cat Wheel",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: toys_images[9],
    prodType: "Toys",
  },
  //WELLNESS
  {
    id: 45,
    prodName: "Biotin Syrup (For Skin and Fur)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[0],
    prodType: "Vitamins",
  },
  {
    id: 46,
    prodName: "Multivitamins Syrup",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[1],
    prodType: "Vitamins",
  },
  {
    id: 47,
    prodName: "Omega-3 Syrup",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[2],
    prodType: "Vitamins",
  },
  {
    id: 48,
    prodName: "Vitamin C Syrup",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[3],
    prodType: "Vitamins",
  },
  {
    id: 49,
    prodName: "Vitamin E Syrup",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[4],
    prodType: "Vitamins",
  },
  {
    id: 50,
    prodName: "Dried Catnip",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[5],
    prodType: "Vitamins",
  },
  {
    id: 51,
    prodName: "Catnip Seeds",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[6],
    prodType: "Vitamins",
  },
  {
    id: 52,
    prodName: "Matatabi Sticks",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[7],
    prodType: "Vitamins",
  },
  {
    id: 53,
    prodName: "Dental Treats (Salmon)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[8],
    prodType: "Vitamins",
  },
  {
    id: 50,
    prodName: "Dental Treats (Chicken)",
    prodPrice: 800,
    prodDescription: "desc",
    prodImg: wellness_images[9],
    prodType: "Vitamins",
  },
];